# Generated by Django 5.2 on 2025-05-09 08:05

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('business_descriptions', models.TextField(max_length=350)),
                ('product_category', models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Handmade', 'Handmade'), ('Home Goods', 'Home Goods'), ('Other', 'other')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('product_descriptions', models.CharField(max_length=100)),
                ('business_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profile', to='main.businessprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('location', models.CharField(default='Dar es salaam', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerlocation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_category', models.CharField(choices=[('Facebook', 'facebook'), ('Instagram', 'instagram'), ('Tiktok', 'tiktok')], default='Instagram', max_length=50)),
                ('handle', models.CharField(max_length=100, validators=[main.models.validate_handle_input])),
                ('product_infos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='main.productinfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearence_count', models.PositiveIntegerField(default=0)),
                ('link_copied_count', models.PositiveIntegerField(default=0)),
                ('new_customers_count', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
