# Generated by Django 5.1.6 on 2025-03-11 18:40

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('product_descriptions', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_category', models.CharField(choices=[('Facebook', 'facebook'), ('Instagram', 'instagram'), ('Ticktok', 'ticktok')], default='Instagram', max_length=10)),
                ('instagram_handle', models.CharField(max_length=30, validators=[main.models.validate_handle_input])),
                ('facebook_handle', models.CharField(max_length=30)),
                ('ticktock_handle', models.CharField(max_length=30)),
                ('product_infos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productinfos')),
            ],
        ),
    ]
