# Generated by Django 5.1.6 on 2025-03-27 11:25

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInfos',
            new_name='ProductInfo',
        ),
        migrations.CreateModel(
            name='SocialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_category', models.CharField(choices=[('Facebook', 'facebook'), ('Instagram', 'instagram'), ('Ticktok', 'ticktok')], default='Instagram', max_length=10)),
                ('handle', models.CharField(max_length=30, validators=[main.models.validate_handle_input])),
                ('product_infos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialInfos',
        ),
    ]
