# Generated by Django 5.2 on 2025-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinfo',
            name='product_infos',
        ),
        migrations.AddField(
            model_name='socialinfo',
            name='product_infos',
            field=models.ManyToManyField(blank=True, related_name='social_handles', to='main.productinfo'),
        ),
    ]
