# Generated by Django 4.2.7 on 2025-03-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_productinfos_productinfo_socialinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'laptop'), ('Fashion', 'tshirt'), ('Furniture', 'couch'), ('Kitchenware', 'utensils')], default='Fashion', max_length=15),
        ),
    ]
