# Generated by Django 5.1.6 on 2025-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productinfo_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='product_category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Kitchenware', 'Kitchenware')], default='Fashion', max_length=15),
        ),
    ]
