# Generated by Django 5.1.6 on 2025-04-03 22:14

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_productinfo_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinfo',
            name='handle',
            field=models.CharField(default='@Placeholder', max_length=30, validators=[main.models.validate_handle_input]),
        ),
    ]
