# Generated by Django 5.1.6 on 2025-04-03 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_socialinfo_product_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinfo',
            name='product_infos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.productinfo'),
        ),
    ]
