# Generated by Django 5.1.6 on 2025-04-06 00:19

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_socialinfo_product_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinfo',
            name='handle',
            field=models.CharField(max_length=30, validators=[main.models.validate_handle_input]),
        ),
    ]
